#!/usr/bin/env python

import argparse
import os
import re
import subprocess
import sys
import socket
import json

COMMAND = 'pgrep'

# nagios exit code
STATUS_OK = 0
STATUS_WARNING = 1
STATUS_ERROR = 2
STATUS_UNKNOWN = 3

def main():

  # parse args

  # build command
  cmd = [COMMAND]

  cmd.append('-u')
  cmd.append('root')
  cmd.append('keepalived')

  cmd.insert(0, "sudo")

  # exec command
  p = subprocess.Popen(cmd,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  output, err = p.communicate()
  output=output.strip().replace('\n', ' ')

  if len(output) == 0:
    print "KEEPALIVED ERROR: keepalived is not running"
    return STATUS_ERROR
  else:
    print "KEEPALIVED OK: keepalived is running. PID: %s" % output
    return STATUS_OK

if __name__ == "__main__":
    sys.exit(main())
